### ISSUE TITLE
User Card View Elements Bugs 

### ISSUE THREAD

**Issue by gedesuryantara** [gedesuryantara/inventaria#3]
Terdapat Bug dalam peletakan user card seperti screen shoot di bawah ini 
![image](https://github.com/gedesuryantara/inventaria/assets/146906693/a7bd40f3-cc51-4969-98b0-e9786463ad74)

**Comment by IPutuWidhyatama21** [comment]
Siap segera ditangani

**Comment by gedesuryantara** [comment]
all done
